### ISSUE TITLE
staking tx example

### ISSUE THREAD

**Issue by roccomuso** [paritytech/txwrapper#264]
Can you share an example of how to create a staking/unstaking transaction?

**Comment by emostov** [comment]
We have an example of how to use `txwrapper` to construct transactions here: https://github.com/paritytech/txwrapper/blob/master/examples/polkadot.ts. This gives the fundamentals of interacting with `txwrapper`. Any parameters specific to a transaction should be noted in its documentation. We don't keep examples of transaction workflows for something like staking in this repo because they are beyond the scope of `txwrapper`. Instead I would recommend first gaining a conceptual understanding of what you are trying to do and then using `txwrapper` to execute the specific transactions you determine are necessary. This guide about nominating on polkadot may be a good starting point: https://wiki.polkadot.network/docs/en/maintain-guides-how-to-nominate-polkadot

If you are purely interested in the implementation details behind one of the staking transactions, here is an example of `staking.bond`: https://github.com/joepetrowski/txintegration/blob/fb9210e66c845b822f5a6eadf3602b58445f3e87/src/payloadConstructors/stakingBond.ts#L33
